---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rundetection-ngem-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: rundetection-ngem-pv-smb
  storageClassName: ""