---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fia-api
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: fia-api
          image: ghcr.io/fiaisis/fia-api@sha256:6989a11b219567a90f3940d9053c760d7055f62196979ea4fcee1ed1bd2a59f2
