---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fia-api
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: fia-api
          image: ghcr.io/fiaisis/fia-api@sha256:d3fd997c6282bc90cc88f17e2632d3db3d25ed414c1e1ce519764a40b743c08c
