---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobcreator
  namespace: fia
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: jobcreator
      containers:
        - name: jobcreator
          env:
            # Non secret env vars
            - name: DB_IP
              value: dbspg-dev.fds.rl.ac.uk
            - name: DB_PORT
              value: "6432"
            - name: DEV_MODE
              value: "True"
