apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  sources:
    - repoURL: https://helm.ngc.nvidia.com/nvidia
      chart: gpu-operator
      targetRevision: v26.3.1
      helm:
        values: |
          mig:
            strategy: none
          daemonsets:
            tolerations:
              - key: "nvidia.com/gpu"
                operator: "Equal"
                value: "worker"
                effect: "NoSchedule"
  destination:
    namespace: gpu-operator
    name: prod
  project: prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  sources:
    - repoURL: https://helm.ngc.nvidia.com/nvidia
      chart: gpu-operator
      targetRevision: v26.3.1
      helm:
        values: |
          mig:
            strategy: none
          operator:
            defaultRuntime: containerd  # Force the operator to use containerd
          toolkit:
            enabled: true
            env:
              - name: CONTAINERD_CONFIG_DIR
                value: /etc/containerd/conf.d
              - name: CONTAINERD_CONFIG
                value: /etc/containerd/conf.d/99-nvidia.toml
          daemonsets:
            tolerations:
              - key: "nvidia.com/gpu"
                operator: "Equal"
                value: "worker"
                effect: "NoSchedule"
  destination:
    namespace: gpu-operator
    name: staging
  project: staging
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true