---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-viewer
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: data-viewer
          image: ghcr.io/fiaisis/data-viewer@sha256:9ed533fb035d53a7ce5c7d994301911679ac32f6ae93d5793c7b57161aa5dc4b
