---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-viewer
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: data-viewer
          image: ghcr.io/fiaisis/data-viewer@sha256:2e70be7e2b6fe4d994a272d057a8ce4f8be256c4795bf564bfad3066402254ad
