---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-landing-page
  namespace: landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-landing-page
  template:
    metadata:
      labels:
        app: management-landing-page
    spec:
      containers:
        - name: management-landing-page
          image: ghcr.io/fiaisis/management-landing-page@sha256:2098bcdc387a036fab98c592690648262ab70d00f3ab42b080e8ed65b8ff6cfe
          ports:
            - name: web-port
              protocol: TCP
              containerPort: 3000
