---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-landing-page
  namespace: landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-landing-page
  template:
    metadata:
      labels:
        app: management-landing-page
    spec:
      containers:
        - name: management-landing-page
          image: ghcr.io/fiaisis/management-landing-page@sha256:bc53bf4e1385cce4122960e1fe92336e7e5009dbb22c97c97e781c2eb79042f3
          ports:
            - name: web-port
              protocol: TCP
              containerPort: 3000
