---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-landing-page
  namespace: landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-landing-page
  template:
    metadata:
      labels:
        app: management-landing-page
    spec:
      containers:
        - name: management-landing-page
          image: ghcr.io/fiaisis/management-landing-page@sha256:4d42404a196fecc3f0926e9ed2b540d23890c1584541da86c5f2265624f94b1c
          ports:
            - name: web-port
              protocol: TCP
              containerPort: 3000
