---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scigateway
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: scigateway
          image: ghcr.io/fiaisis/scigateway@sha256:5871db045fb94e8bfdcd871cdd062090e2198b8e1aba37af1c9419dc4f205c46
