---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scigateway
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: scigateway
          image: ghcr.io/fiaisis/scigateway@sha256:09c0d02081a8b2a25390a489d2c09b8a6382f276a441919247bdff1dd997d1ff
