---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scigateway
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: scigateway
          image: ghcr.io/fiaisis/scigateway@sha256:4531fd1fb5b795cc4e1e334956b23392962e846f04a9bab67352e5427a76b313
