---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundetection
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: rundetection
          image: ghcr.io/fiaisis/rundetection@sha256:97fdf7436b5a4e25d528da23caf0862a1cbe84f129c2815cdea41184bfefb39f
