---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundetection
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: rundetection
          image: ghcr.io/fiaisis/rundetection@sha256:237eba6ecb3f5d311db07ee8611a644af42b686bc6a8e718827b411f4d08546f
