---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundetection
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: rundetection
          image: ghcr.io/fiaisis/rundetection@sha256:59fae961afddf6f4761438e19141e36d232abc25f025e3b86f7a977fa2da4cb6
