---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plotting-service
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: plotting-service
          image: ghcr.io/fiaisis/plotting-service@sha256:242c754c41c0e16cc4e7413e9ff3afe40367dc1bc98aa8a1401bc262011207e6
