---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plotting-service
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: plotting-service
          image: ghcr.io/fiaisis/plotting-service@sha256:53e709dc4e949cf9db31db15c4aabd951e8251e581844bf8cffcd8749f50beba
