---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plotting-service
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: plotting-service
          image: ghcr.io/fiaisis/plotting-service@sha256:2a00fe974bfc9ae51dc6a0264082721978c97a04fa3466e90a899d1d3ba636f1
