---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-watcher-operator
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: file-watcher-operator
          image: ghcr.io/fiaisis/filewatcher-operator@sha256:012227899c4916224d722d36076e8ad490344d82458d0e2fc040c43fee2b8f84
          env:
            - name: FILE_WATCHER_SHA256
              value: "dfb101352b0ee0415d443572c1e4072caa9fc917187f9986cec1addbc3ff4e3a"
