---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-watcher-operator
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: file-watcher-operator
          image: ghcr.io/fiaisis/filewatcher-operator@sha256:ba59af9143941d194f4f1809bdec9b8b4923853d7cde258616d66ebd7c49f0be
          env:
            - name: FILE_WATCHER_SHA256
              value: "91aba2f4a8d3eacb7fd050170d721a276639e8372833fcf311b03b4706460ff7"
