---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-watcher-operator
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: file-watcher-operator
          image: ghcr.io/fiaisis/filewatcher-operator@sha256:1094c35a30167b4ed218d078e26d29d08af70e14b07e30d9533a49967218c333
          env:
            - name: FILE_WATCHER_SHA256
              value: "1afb3210153590619182759801a614eb7b0f408714d48735eef02dfcdd4124c7"
