---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobcreator
  namespace: fia
spec:
  template:
    spec:
      serviceAccountName: jobcreator
      containers:
        - name: jobcreator
          image: ghcr.io/fiaisis/jobcreator@sha256:e9d4c9da1267e07d007f830463a749ca7e2debd8a5e43030e0237595f7282462
          env:
            - name: WATCHER_SHA
              value: 381bdb923b73d11bb3c58bf67fce871689ce0e25e7c0d27a82b9cbbbbe766cdd
            - name: DEFAULT_RUNNER_SHA
              value: 2df6f27ac93304c59d97cfd618236534b81491c8425a766a3aef89658d026811
            - name: IMAGING_RUNNER_SHA
              value: d4c58e2fccce5c8ad6518147a0ba6559dd698bff9c0823159287ff2c204259e7
