---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobcreator
  namespace: fia
spec:
  template:
    spec:
      serviceAccountName: jobcreator
      containers:
        - name: jobcreator
          image: ghcr.io/fiaisis/jobcreator@sha256:fec338dabf9cdb1c88cb186e61743f093154b1ee16a5d5454994ff723612ae6f
          env:
            - name: WATCHER_SHA
              value: 99d64c791be0493635c3b8e09c1db5472d0dd5c7545a7f41a356571db412bd2e
            - name: DEFAULT_RUNNER_SHA
              value: 2df6f27ac93304c59d97cfd618236534b81491c8425a766a3aef89658d026811
            - name: IMAGING_RUNNER_SHA
              value: d4c58e2fccce5c8ad6518147a0ba6559dd698bff9c0823159287ff2c204259e7
