---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobcreator
  namespace: fia
spec:
  template:
    spec:
      serviceAccountName: jobcreator
      containers:
        - name: jobcreator
          image: ghcr.io/fiaisis/jobcreator@sha256:05eebe636de2dd24cc186dabc88ec907d07b98cecfa3ccf1035f5ae6a4abd94a
          env:
            - name: WATCHER_SHA
              value: d1a0311516f4f04995242c1618e4cb910852794b18b329d367df1b852c439200
            - name: DEFAULT_RUNNER_SHA
              value: 2df6f27ac93304c59d97cfd618236534b81491c8425a766a3aef89658d026811
            - name: IMAGING_RUNNER_SHA
              value: d4c58e2fccce5c8ad6518147a0ba6559dd698bff9c0823159287ff2c204259e7
