---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fia-auth
  namespace: fia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fia-auth
  template:
    metadata:
      labels:
        app: fia-auth
    spec:
      containers:
        - name: fia-auth
          image: ghcr.io/fiaisis/fia-auth@sha256:cf93af46c066a74458f10317e40d44b67305495c2bbd296dcbee1b56629507e5
