---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fia-auth
  namespace: fia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fia-auth
  template:
    metadata:
      labels:
        app: fia-auth
    spec:
      containers:
        - name: fia-auth
          image: ghcr.io/fiaisis/fia-auth@sha256:e2225c606bee5c1b552b2c8aa9f27c450cef38c4bb3140b25a00f2450f4bd290
