---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fia-auth
  namespace: fia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fia-auth
  template:
    metadata:
      labels:
        app: fia-auth
    spec:
      containers:
        - name: fia-auth
          image: ghcr.io/fiaisis/fia-auth@sha256:bd13617df89d57ce4a997bc1858f749d2194af53ba4ab731f16586984998c01f
