---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scigateway
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: scigateway
          image: ghcr.io/fiaisis/scigateway@sha256:8f5194a5036c1c64113791567afb2ff32d28ecd7dda987db9a1371154a5393e3
