---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scigateway
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: scigateway
          image: ghcr.io/fiaisis/scigateway@sha256:2eb141425a82232f067591d732e336a3a8253b0f20e53ba25caf16c41281445b
