---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-watcher-operator
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: file-watcher-operator
          image: ghcr.io/fiaisis/filewatcher-operator@sha256:0944285ecf0aa2ac7a4fc098b0cdc6a50746e5d6c6f90df0452486fd7bd9d221
          env:
            - name: FILE_WATCHER_SHA256
              value: "3d49a781671bed5a79bab20982308a2d5544150d299628fd90993a796efad449"
