---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-watcher-operator
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: file-watcher-operator
          image: ghcr.io/fiaisis/filewatcher-operator@sha256:e92463c174e92060982782563fcd001b237624bbfcea0ed445a6fb701f8cd1f0
          env:
            - name: FILE_WATCHER_SHA256
              value: "91aba2f4a8d3eacb7fd050170d721a276639e8372833fcf311b03b4706460ff7"
