---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-viewer
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: data-viewer
          image: ghcr.io/fiaisis/data-viewer@sha256:57b312d451f0f8001d72698c5d130fd73d463eec26b2c3727e687dc8fb5a7d20
