---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: imat-smb-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: imat-pv-smb
  storageClassName: ""