---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llsp-api
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: llsp-api
          image: ghcr.io/fiaisis/llsp-api@sha256:ee2f158764b0953bda891bf36ceed96b8d092e85ce0a8fc6d429fd084629e449
