---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llsp-api
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: llsp-api
          image: ghcr.io/fiaisis/llsp-api@sha256:148da54d6a28d0c07d2068262709b86cdf96643bcad49cfa35cd3e1fc123701a
