---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llsp-api
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: llsp-api
          image: ghcr.io/fiaisis/llsp-api@sha256:4a18ea9189ed4d599705e5ff5a17500ad1553d36c571552e0ec6efb16ab70472
