---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-data-operator
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: live-data-operator
          image: ghcr.io/fiaisis/live-data-operator@sha256:4315007179c501d7b48b1d15616b28e30c6098852dc306cb7eeccbffc5e94fd6
          env:
            - name: LIVE_DATA_PROCESSOR_IMAGE_SHA
              value: "1e4546b2e9761dbb20b292e0ced54d6012ffdfa0afa353a8935187b135449edf"
