---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-data-operator
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: live-data-operator
          image: ghcr.io/fiaisis/live-data-operator@sha256:fdb523cb03544c1d8d5e7113a6d7e3748f1449c18dcb8cdae7b8f4dc8e8cdf32
          env:
            - name: LIVE_DATA_PROCESSOR_IMAGE_SHA
              value: "b280d96f3834f1a4d54db9301b9bda816d329174159fdf96ad87368b8102ec13"
