---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/fiaisis/frontend@sha256:62aa3b82691f3e54a59c2d923f45e4d8444a8e88c2b9cc5cc1be475f491e9c9d
