---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundetection
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: rundetection
          image: ghcr.io/fiaisis/rundetection@sha256:25fb70223685c549b517b25ad7817a56fb3e2ad8b2cd45b9b94b69f6f174a06b
