---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundetection
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: rundetection
          image: ghcr.io/fiaisis/rundetection@sha256:780cb2c5e2397460efc5b372200a71bef0e109e350c23136e26805baf270b21d
