---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundetection
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: rundetection
          image: ghcr.io/fiaisis/rundetection@sha256:d7ea8b4cb6dd8c86c0c88ff19875996dd48dd5ac9d5dbc35c8f83ea994664bdc
