---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/fiaisis/frontend@sha256:858319fd7d0d5a752bdb01bea6ce2dff192dc763c42b4f487d2741df81e5e717
