---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/fiaisis/frontend@sha256:dcaf84e4bda3d63ba0dcecec6b7519672ed1b209f08d266a4639cf1205f2882f
