---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llsp-worker
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: llsp-worker
          image: ghcr.io/fiaisis/llsp-worker@sha256:b5529535c3b086d61781f5821f4ea0c039fb473498891de75413ef2c7e9cc1d3
