---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llsp-worker
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: llsp-worker
          image: ghcr.io/fiaisis/llsp-worker@sha256:86466cc8a4efaaca1fda397d191fa0ed1521e44200c830327829ad02f7893248
