---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llsp-worker
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: llsp-worker
          image: ghcr.io/fiaisis/llsp-worker@sha256:2777acd0479d69ea8f781b2d39471d3fda13f1d2841b7b6a2a93ddd10ee3c0e4
