---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fia-api
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: fia-api
          image: ghcr.io/fiaisis/fia-api@sha256:9e44e2ea33f0c71226ce6428b567665fa4af9853c01770105edad5bb8cd1fbfe
