---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fia-api
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: fia-api
          image: ghcr.io/fiaisis/fia-api@sha256:fb492a266382b181b28c5df30f1020001a10fcf224e60493d40e756b09892ec1
