---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plotting-service
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: plotting-service
          image: ghcr.io/fiaisis/plotting-service@sha256:3f37c19fa74741ad75621747450559642d1141a718832a91244ac6dece6599ec
