---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plotting-service
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: plotting-service
          image: ghcr.io/fiaisis/plotting-service@sha256:ba052f9d366de33142f400598ceae2c5b6be22430a68447936a96f1dd533f5f3
