---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-data-operator
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: live-data-operator
          image: ghcr.io/fiaisis/live-data-operator@sha256:2ffb4c3078e24e0172564cfb40b118311589b3fa66fc2a41de7120c179b36e40
          env:
            - name: LIVE_DATA_PROCESSOR_IMAGE_SHA
              value: "6f23eba8ce841d95d6b53a16c24a1c6f9698f9739b597d186e17e60c77a2a83b"