---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-data-operator
  namespace: fia
spec:
  template:
    spec:
      containers:
        - name: live-data-operator
          image: ghcr.io/fiaisis/live-data-operator@sha256:8ec39f44e919e7e355699580d531d4ad224cdf792bf1b47bbfd52af7c74c2bf4
          env:
            - name: LIVE_DATA_PROCESSOR_IMAGE_SHA
              value: "c1269f426e68dda14c822635bd08eee0b81de29118c9d184e821fac6bb08da0d"