apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
components:
- ../../variants/prod
patches:
- path: envoy-proxy.yml
- path: gateway.yml
- path: redirect-http-route.yml