---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 9.4.17
    chart: argo-cd
    helm:
      values: |
        configs:
          params:
            server.rootpath: argocd
        redis-ha:
          enabled: true

        controller:
          replicas: 2

        server:
          autoscaling:
            enabled: true
            minReplicas: 2
          httproute:
            enabled: true
            hostnames: management.reduce.isis.cclrc.ac.uk
            parentRefs:
              - group: gateway.networking.k8s.io
                kind: Gateway
                name: envoy-gateway
                namespace: envoy-gateway-system
                sectionName: https-main
            rules:
              - matches:
                - path:
                  type: PathPrefix
                  value: /argocd

        repoServer:
          autoscaling:
            enabled: true
            minReplicas: 2

        applicationSet:
          replicas: 2
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true